language: java
jdk:
  - openjdk8

before_script:
  - chmod +x gradlew
  - chmod +x ./gradlew

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

#script: "./gradlew clean build"